#!/usr/bin/env python3

import sys
import os.path

# allow importing the framework code
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'framework'))

# lazily assume these will all be in the same directory
sys.path.append(os.path.dirname(sys.argv[1]))

for f in sys.argv[1:]:
    __import__(os.path.basename(f)[0:-3])
