#!/usr/bin/env ruby

RBC = false

class Base
  def self.dsl(name, value)
    define_method("dsl_#{name}".to_sym) do
      instance_variable_get("@#{name}") || value
    end

    define_method("dsl_#{name}=".to_sym) do |v|
      instance_variable_set("@#{name}", v)
    end
  end
end

if RBC
  require 'fileutils'

  ARGV.each do |f|
    rbc_f = File.join(File.dirname(f), "__rbcache__", File.basename(f))
    if File.exist?(rbc_f)
      iseq = RubyVM::InstructionSequence.load_from_binary(File.read(rbc_f))
    else
      iseq = RubyVM::InstructionSequence.compile_file(f)
      FileUtils.mkdir_p(File.dirname(rbc_f))
      File.write(rbc_f, iseq.to_binary)
    end

    iseq.eval
  end
else
  ARGV.each { |f| require(File.expand_path(f)) }
end
